// authcraft-velocity/build.gradle
plugins {
    id 'java'
}

dependencies {
    implementation project(':authcraft-core')
    implementation project(':authcraft-storage')
    implementation project(':authcraft-security')

    compileOnly 'com.velocitypowered:velocity-api:3.3.0-SNAPSHOT'
    annotationProcessor 'com.velocitypowered:velocity-api:3.3.0-SNAPSHOT'
}

def pluginVersion = version

tasks.jar {
    dependsOn ':authcraft-core:jar', ':authcraft-storage:jar', ':authcraft-security:jar'
    
    archiveBaseName.set('AuthCraft-Velocity')
    archiveClassifier.set('')
    archiveVersion.set(pluginVersion.toString())
    
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    exclude 'META-INF/*.SF', 'META-INF/*.DSA', 'META-INF/*.RSA', 'META-INF/DEPENDENCIES', 'META-INF/LICENSE*', 'META-INF/NOTICE*'
}
