// com/authcraft/core/crypto/TOTPProvider.java
package com.authcraft.core.crypto;

import com.authcraft.core.api.TwoFactorProvider;
import com.authcraft.core.model.TwoFactorMethod;
import com.google.zxing.BarcodeFormat;
import com.google.zxing.EncodeHintType;
import com.google.zxing.WriterException;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.QRCodeWriter;
import com.warrenstrange.googleauth.GoogleAuthenticator;
import com.warrenstrange.googleauth.GoogleAuthenticatorKey;
import com.warrenstrange.googleauth.GoogleAuthenticatorConfig;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;

/**
 * TOTP (Google Authenticator) 2FA provider.
 */
public class TOTPProvider implements TwoFactorProvider {

    private static final String ISSUER = "AuthCraft";
    private final GoogleAuthenticator gAuth;

    public TOTPProvider() {
        GoogleAuthenticatorConfig gAuthConfig =
                new GoogleAuthenticatorConfig.GoogleAuthenticatorConfigBuilder()
                        .setWindowSize(3) // ±1 time step tolerance
                        .setCodeDigits(6)
                        .setTimeStepSizeInMillis(30000) // 30 seconds
                        .build();
        this.gAuth = new GoogleAuthenticator(gAuthConfig);
    }

    @Override
    public TwoFactorMethod getMethod() {
        return TwoFactorMethod.TOTP;
    }

    @Override
    public String generateSecret(UUID playerUuid, String username) {
        GoogleAuthenticatorKey key = gAuth.createCredentials();
        return key.getKey();
    }

    @Override
    public boolean verifyCode(String secret, String code) {
        try {
            // Validate code format first (must be exactly 6 digits)
            String trimmedCode = code.trim();
            if (trimmedCode.length() != 6 || !trimmedCode.matches("\\d{6}")) {
                return false;
            }
            int codeInt = Integer.parseInt(trimmedCode);
            // GoogleAuthenticator uses constant-time comparison internally
            return gAuth.authorize(secret, codeInt);
        } catch (NumberFormatException e) {
            return false;
        }
    }

    @Override
    public CompletableFuture<Boolean> sendCode(String target, String code) {
        // TOTP does not send codes — generated by user's app
        return CompletableFuture.completedFuture(true);
    }

    @Override
    public byte[] generateQrCode(String secret, String username, int size) {
        // This method is kept for backward compatibility
        String otpAuthUrl = getQrCodeUrl(secret, username);
        try {
            QRCodeWriter writer = new QRCodeWriter();
            BitMatrix matrix = writer.encode(
                otpAuthUrl, BarcodeFormat.QR_CODE, size, size,
                Map.of(EncodeHintType.MARGIN, 1)
            );
    
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            MatrixToImageWriter.writeToStream(matrix, "PNG", baos);
            return baos.toByteArray();
        } catch (WriterException | IOException e) {
            throw new RuntimeException(
                "Failed to generate QR code", e
            );
        }
    }
    
    /**
     * Generate the otpauth:// URL for the QR code.
     */
    public String getQrCodeUrl(String secret, String username) {
        return String.format(
            "otpauth://totp/%s:%s?secret=%s&issuer=%s&digits=6&period=30",
            URLEncoder.encode(ISSUER, StandardCharsets.UTF_8),
            URLEncoder.encode(username, StandardCharsets.UTF_8),
            secret,
            URLEncoder.encode(ISSUER, StandardCharsets.UTF_8)
        );
    }

    @Override
    public boolean isAvailable() {
        return true; // TOTP is always available
    }
}