plugins {
    id 'java'
}

dependencies {
    implementation project(':authcraft-core')
    implementation 'io.javalin:javalin:5.6.3'
    implementation 'io.javalin:javalin-rendering:5.6.3'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.16.1'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.16.1'
    implementation 'org.slf4j:slf4j-api:2.0.9'
    implementation 'org.slf4j:slf4j-simple:2.0.9'
    implementation 'io.jsonwebtoken:jjwt-api:0.12.3'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.3'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.3'
}

jar {
    manifest {
        attributes 'Implementation-Title': 'AuthCraft-Web',
                   'Implementation-Version': version
    }
}
