// com/authcraft/core/model/AuditEventType.java
package com.authcraft.core.model;

public enum AuditEventType {
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    LOGOUT,
    REGISTER,
    PASSWORD_CHANGE,
    TWO_FACTOR_ENABLE,
    TWO_FACTOR_DISABLE,
    TWO_FACTOR_RESET,
    ACCOUNT_LOCKED,
    ACCOUNT_UNLOCKED,
    ACCOUNT_UNLOCK,
    IP_BLOCKED,
    BOT_DETECTED,
    UNICODE_SPOOF_DETECTED,
    SESSION_CREATED,
    SESSION_EXPIRED,
    ROLE_CHANGED,
    SECURITY_AUDIT,
    MIGRATION,
    BACKUP_CODE_USED,
    RECOVERY_INITIATED,
    RECOVERY_COMPLETED,
    DATA_EXPORT,
    DELETION_REQUESTED,
    DELETION_CANCELLED,
    DELETION_COMPLETED,
    AUDIT_EXPORT,
    CUSTOM
}